### PR TITLE
Change the phrasing of some scentences so they read more clearly.

### PR DESCRIPTION
**Pull request by curiouslittledroid**
Just started playing with Macaw, and reading the docs. Some of the sentences were a little confusing, so I fixed them :-)

### CODE REVIEW

**Comment by btjones** [comment]
Thanks for this! Can you remove the .gitignore comment that was added before we merge?

**Comment by curiouslittledroid** [comment]
I just looked at the git logs on my end and I have not committed a gitignore.
I have one present (to exclude my phpstore ide files), but I have not checked it in.
Any suggestion ?

**Comment by btjones** [comment]
Hm, it's definitely showing that "you" added a .gitignore (you in quotation marks because it appears to have been auto-generated):
https://github.com/pcaithness/docs/commit/21a059c2632833074d6dbae50c605f7adac0bf37
https://github.com/macawco/docs/pull/22/files

**Comment by curiouslittledroid** [comment]
Hmm.
OK, Scrap that pull request. I'll redo it and send you another pull request.
I have a gitignore plugin installed into phpstorm, nut never found it overly useful. Maybe that did it automagically.
Maybe I'll kill that too.

**Pull request merged**
